// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Wr13cCD347Khl8CV4KqZ_ZqpAA78Luo',
    appId: '1:972401900948:web:dfcc3df7c9bd3301552381',
    messagingSenderId: '972401900948',
    projectId: 'infoev-456907',
    authDomain: 'infoev-456907.firebaseapp.com',
    storageBucket: 'infoev-456907.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_a1bBEkFSAMMfRO6UgMvqA_Fb_8Ensd0',
    appId: '1:972401900948:android:e343b9874d8bf02d552381',
    messagingSenderId: '972401900948',
    projectId: 'infoev-456907',
    storageBucket: 'infoev-456907.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjZhTPf4BgHbYk0gOwU50EJKoKpQ82RfU',
    appId: '1:972401900948:ios:1e2c2352db51e75a552381',
    messagingSenderId: '972401900948',
    projectId: 'infoev-456907',
    storageBucket: 'infoev-456907.firebasestorage.app',
    androidClientId:
        '972401900948-1bf48oentfq96pmtuq32hc44mbdio66e.apps.googleusercontent.com',
    iosBundleId: 'id.ginio.infoev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjZhTPf4BgHbYk0gOwU50EJKoKpQ82RfU',
    appId: '1:972401900948:ios:ebd0a97f256c8aa1552381',
    messagingSenderId: '972401900948',
    projectId: 'infoev-456907',
    storageBucket: 'infoev-456907.firebasestorage.app',
    androidClientId:
        '972401900948-1bf48oentfq96pmtuq32hc44mbdio66e.apps.googleusercontent.com',
    iosBundleId: 'com.example.infoev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7Wr13cCD347Khl8CV4KqZ_ZqpAA78Luo',
    appId: '1:972401900948:web:2890bfafd221b127552381',
    messagingSenderId: '972401900948',
    projectId: 'infoev-456907',
    authDomain: 'infoev-456907.firebaseapp.com',
    storageBucket: 'infoev-456907.firebasestorage.app',
  );
}
