// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd2JRRLH97iMxgaSC5gkosjmG0yZhv_6Y',
    appId: '1:769140553684:web:91e2f551ade16b506e4841',
    messagingSenderId: '769140553684',
    projectId: 'celtic-volt-462608-h5',
    authDomain: 'celtic-volt-462608-h5.firebaseapp.com',
    storageBucket: 'celtic-volt-462608-h5.firebasestorage.app',
    measurementId: 'G-S0FSLFEH4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALwIklfJ089DHj10lko1j5Ajxc1DfBJfk',
    appId: '1:769140553684:android:e336135f76803d1e6e4841',
    messagingSenderId: '769140553684',
    projectId: 'celtic-volt-462608-h5',
    storageBucket: 'celtic-volt-462608-h5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXbPoqDI2DpXAa5tK4xPcTRN4G4NoNesc',
    appId: '1:769140553684:ios:6b6d2b94ca38fbfc6e4841',
    messagingSenderId: '769140553684',
    projectId: 'celtic-volt-462608-h5',
    storageBucket: 'celtic-volt-462608-h5.firebasestorage.app',
    androidClientId: '769140553684-76qk2u5kor561s1klo7gpvr0an34oahg.apps.googleusercontent.com',
    iosBundleId: 'id.ginio.infoev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXbPoqDI2DpXAa5tK4xPcTRN4G4NoNesc',
    appId: '1:769140553684:ios:ea8ed64f9f0b9b596e4841',
    messagingSenderId: '769140553684',
    projectId: 'celtic-volt-462608-h5',
    storageBucket: 'celtic-volt-462608-h5.firebasestorage.app',
    androidClientId: '769140553684-76qk2u5kor561s1klo7gpvr0an34oahg.apps.googleusercontent.com',
    iosBundleId: 'com.example.infoev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd2JRRLH97iMxgaSC5gkosjmG0yZhv_6Y',
    appId: '1:769140553684:web:73ecf3cce6cd29016e4841',
    messagingSenderId: '769140553684',
    projectId: 'celtic-volt-462608-h5',
    authDomain: 'celtic-volt-462608-h5.firebaseapp.com',
    storageBucket: 'celtic-volt-462608-h5.firebasestorage.app',
    measurementId: 'G-0JE6T48ZEX',
  );

}